### ISSUE TITLE
Dashboard->vue-json-pretty->exception

### ISSUE THREAD

**Issue by iget** [dotnetcore/CAP#1016]
Dashboard Bug .
long type value JSON display exception.

vue-json-pretty

![image](https://user-images.githubusercontent.com/6291948/136921569-8b4f7ec8-e8a1-477a-8f16-51158ea8aa0f.png)

**Comment by yang-xiaodong** [comment]
This is because javascript not support long type ,
see https://stackoverflow.com/questions/66355403/c-sharp-asp-net-passing-an-object-with-a-long-property-to-front-end-changes-its?noredirect=1&lq=1

Same as msg-id, either convert to string or don’t deal with this issue. Would like to mark a PR to fix?
