### ISSUE TITLE
Allow to inverse usage of outbox pattern

### ISSUE THREAD

**Issue by remotenode** [dotnetcore/CAP#1051]
Currently, all events are written to persistent storage before it's published to a broker, this is fine, except for cases where every millisecond does really matter.

I propose to try to publish an event to a broker, if it fails, only then send it to persistent storage.

By default, this feature could be turned off, no breaking changes

What do you think?

If I create PR, will you review/merge it?

**Comment by yang-xiaodong** [comment]
No, this does not meet our goal, we are a distributed transaction solution based on local tables, not just as an EventBus. In this way, if the Broker behaves unexpectedly, the message may be lost.

**Comment by artem-avanesov** [comment]
> if the Broker behaves unexpectedly, the message may be lost.

That's why first I propose to try to send message to the broker, if it's unavailable, send it to the database

**Comment by yang-xiaodong** [comment]
Our overall design is based on the premise of storage. This is not only reflected in the sending process, but in the receiving aspect, CAP first stores the message in the database, and then Ack to the Broker instead of waiting for the consumer to succeed.  So the message is in the memory at this time, if the application crashes or terminates, all the messages in the memory will be lost. In addition, for failed messages, if the retry succeeds, the status of the message needs to be updated or deleted.

For your scenario, since CAP will call IDataStorage interface to change the message state when an exception occurs, so you can customize IDataStorage to store or delete messages when the state changes, and then judge the state internally to store only the failed messages.
