### ISSUE TITLE
[Question] How do we handle a situation where consumer and publisher broker address is different?

### ISSUE THREAD

**Issue by ehtesam4m** [dotnetcore/CAP#1058]
I have been looking at this library and it's really awesome. Thanks for the great work. I have two questions. 
1. How do we handle a situation where consumer and publisher broker address is different? For example, If I am consuming from one broker and publishing to another broker.
2. Can we have multiple publisher and consumer? For example: if we are publishing and consuming from multiple brokers in the same application, is it possible to do it?

P.S: We are using Kafka

**Comment by yang-xiaodong** [comment]
Hello,

We currently do not provide direct support for this, but there is a way to achieve it, you can check this comment to get details

https://github.com/dotnetcore/CAP/issues/998#issuecomment-988659781

**Comment by ehtesam4m** [comment]
Hi, Thanks for the quick reply. For multi publisher situation, do they use separate "Published" table or the same table? If same, can we configure separate tables? Are there any work around for multi/different broker subscriber?

**Comment by yang-xiaodong** [comment]
It depends on your configuration, but I think different tables should be used because they need to be isolated from each other.

For multi-instance consumers, you can customize [IConsumerServiceSelector](https://github.com/dotnetcore/CAP/blob/master/src/DotNetCore.CAP/Internal/IConsumerServiceSelector.Default.cs) to get different instances To its corresponding consumers and exclude subscribers from other instances, all these behaviors require you to have sufficient knowledge of this library and fully test it
