### ISSUE TITLE
Support Google Spanner as a storage media

### ISSUE THREAD

**Issue by jhafzoff** [dotnetcore/CAP#1392]
Hi, 
I would like to add support for Google Spanner Database.

**Comment by yang-xiaodong** [comment]
Hello,

Thanks for your PR, since we do not use GCP and our team is unfamiliar with Google Spanner, so I would suggest that this could be written into our docs as a community supported extension and you as the maintainer, what do you think?

Community supported list docs:
https://cap.dotnetcore.xyz/user-guide/en/storage/general/#community-supported-extensions

Thank you.

**Comment by jhafzoff** [comment]
> Hello,
> 
> Thanks for your PR, since we do not use GCP and our team is unfamiliar with Google Spanner, so I would suggest that this could be written into our docs as a community supported extension and you as the maintainer, what do you think?
> 
> Community supported list docs: https://cap.dotnetcore.xyz/user-guide/en/storage/general/#community-supported-extensions
> 
> Thank you.

That sounds great.

**Comment by jhafzoff** [comment]
just for clarification who is your team? isn't CAP an open-source library? I'm just intrigue. 

Thanks.

**Comment by jhafzoff** [comment]
just wondering, how I can become part of the team?

**Comment by yang-xiaodong** [comment]
For members, we are an invitation system. Simply speaking, based on the community contribution to CAP, I will apply to the NCC community and assist in joining. The CAP Team I mentioned means CAP Committers.
