### ISSUE TITLE
Could not associate Cap.OpenTelemetry lineage with user request lineage

### ISSUE THREAD

**Issue by rezamadadi** [dotnetcore/CAP#1403]
Hi,

I want to relate the Cap.OpenTelemetry lineage with the user request lineage
When I checked the code, I noticed that if the resource name is not equal to "OpenTelemetry.Instrumentation.AspNetCore:, a new activity is started.

Activity.Current.Source.Name == "OpenTelemetry.Instrumentation.AspNetCore"

```
                    if (Activity.Current != null &&
                            Activity.Current.Source.Name == "OpenTelemetry.Instrumentation.AspNetCore")
                        _contexts.TryAdd(eventData.Message.GetId(), parentContext = Activity.Current.Context);
                    else
                        Activity.Current = null;

```

**Comment by yang-xiaodong** [comment]
Hi,

I don't know if your problem is related to #1402. By default, the Activity from the request initiated by Asp.Net Core to the CAP event storate is linear. You can see this from [this picture](https://cap. dotnetcore.xyz/img/opentelemetry.png) can be seen.

> if the resource name is not equal to "OpenTelemetry.Instrumentation.AspNetCore", a new activity is started.

Yes, we will only continue the context of ASP.NET Core. If your events come from other heterogeneous systems, the Activity cannot be obtained and used.

Also, if you encounter issue #1100, which is known, we welcome PRs

**Comment by yang-xiaodong** [comment]
No response, closed
