### ISSUE TITLE
Resiliency on start-up. 

### ISSUE THREAD

**Issue by carlsixsmith** [dotnetcore/CAP#1477]
Using CAP in development, when calling 

`
options.UseSqlServer("connectionstring");
`

The CAP bootstrap fails with

> A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - An established connection was aborted by the software in your host machine.)

Because the SQL (running in a container) isn't ready. What is the recommended way of getting the start-up to be more resilient, I've try wrapping the AddCAP in a retry polly block, but it looks like the exception is not bubbling up and therefore not retrying.

**Comment by 3ldar** [comment]
The startup process goes like this: Bootstrapper runs first and then it calls a service method `IStorageInitializer.InitializeAsync`. A possible workaround is to implement your own `IStorageInitializer` service that utilizes a retry policy. But be aware this will delay your application startup.

**Comment by 3ldar** [comment]
@carlsixsmith Since your SQL server running in a container you can utilize docker compose's `depends_on` feature. You can check this [SO](https://stackoverflow.com/questions/60539114/how-to-wait-for-mssql-in-docker-compose) question for the details.

**Comment by yang-xiaodong** [comment]
@carlsixsmith 

@3ldar's answer is correct, this is the design, because CAP needs to initialize the database table, so a  onready database is required.

You should not use Polly, if the CAP startup fails then the web host startup should fail.

If you are in docker-compose, please refer to @3ldar's answer.

If you deploy in kubernetes, you can use `initContainer` (this is equivalent to `depends_on`) or simply use `initialDelaySeconds` of Pod `livenessProbe` to let  kubernetes restart the Pod.
