### ISSUE TITLE
.NET 8 CAP is causing high latency responses in web apis when deployed to azure app service

### ISSUE THREAD

**Issue by preezie-yasir** [dotnetcore/CAP#1488]
While performance testing our .NET 8 api's, we came to conclusion CAP is causing some latency spikes every now and then even if an endpoint does not use CAP at all! We suspect this might be some sort of middleware before or after the request is executed causing these massive inconsistent delays in api responses from time to time.

The following code is a very simple stripped down .NET 8 minimal api to replicate the issue:
![image](https://github.com/dotnetcore/CAP/assets/115682529/744cb906-832a-4fdb-8e6e-5884afa0688a)

Locally, when performance testing, the responses seem to be fine and consistent
![image](https://github.com/dotnetcore/CAP/assets/115682529/081269ec-eef9-4ca0-b2c6-90d7e157be97)

However, once deployed to our azure app service, responses should return consistently after a Thread.sleep of 50ms but when performance testing using postman, we get the following spikes (sometimes responses taking up to 370ms to return!):
![image](https://github.com/dotnetcore/CAP/assets/115682529/74cc2601-cd9e-4531-913d-95e2876f5129)

**Comment by preezie-yasir** [comment]
Heres what our AddInMemoryCap methods look like:
![image](https://github.com/dotnetcore/CAP/assets/115682529/a0115ec7-7bf3-42f3-911d-4596a56e0ca6)

It also happens when adding cap using postgresql
![image](https://github.com/dotnetcore/CAP/assets/115682529/45b30c6e-9b36-41b9-beec-aac86fe1a75b)

**Comment by yang-xiaodong** [comment]
CAP does not depend on the ASP.NET Core SDK `Microsoft.NET.Sdk.Web`, nor does it have any middleware. Only the Dashboard depend ASP.NET Core.

**Comment by yang-xiaodong** [comment]
@preezie-yasir  Answer from ChatGPT

When you insert `Thread.Sleep(50)` in an endpoint to simulate a delay in an ASP.NET Core application, observing response times exceeding the expected 50ms, sometimes even over 300ms, can be attributed to several factors:

1. **Thread Scheduling and Context Switching**: Using `Thread.Sleep` essentially tells the thread manager to suspend the current thread temporarily. After suspension, the thread does not resume immediately once the sleep duration is over; it must wait for the thread scheduler to allocate processor time to it again. In high-concurrency scenarios, this scheduling delay can significantly add to the response time.

2. **Thread Pool Utilization**: ASP.NET Core uses a thread pool to handle requests by default. The thread pool has a limited number of threads, and if there are many concurrent requests, new requests might have to wait in the thread pool queue until a thread becomes available. This waiting time adds to the overall response time.

3. **Resource Contention and Lock Waiting**: If there are locks (e.g., `lock` statements) or other synchronization mechanisms (e.g., `SemaphoreSlim`, `Monitor`, etc.) used elsewhere in your application, concurrent requests might be delayed waiting to acquire locks.

4. **I/O Operations**: If your endpoint performs I/O operations (like database queries, file reads/writes, network requests, etc.) before or after the `Thread.Sleep`, the delays from these operations will also add to the response time.

5. **Garbage Collection**: .NET applications perform garbage collection (GC) to reclaim unused memory. GC can cause the application to pause, especially during a full garbage collection, affecting response times.

To accurately test and measure the concurrency performance of an ASP.NET Core application, it's recommended to use asynchronous operations (like `Task.Delay` instead of `Thread.Sleep`) to simulate delays. This allows for more efficient use of threads, reducing the consumption of thread pool resources and minimizing delays caused by thread suspension. Additionally, employing dedicated performance testing tools (such as Apache JMeter, Artillery, Locust, etc.) can help simulate concurrent requests more accurately and analyze the application's performance effectively.

**Comment by preezie-yasir** [comment]
It happens even when i dont have a Thread.Sleep. I was testing before with a cosmosdb cache call and it was still spiking at times

**Comment by preezie-yasir** [comment]
Here is an example of code which just has a simple get endpoint that fetches something from cosmos cache:
![image](https://github.com/dotnetcore/CAP/assets/115682529/f40dbdab-8c82-4420-96f9-8958d9fe86b9)

When i deploy to azure and performance test the api's, i get massive random spikes sometimes reaching over 1000ms to respond!
![image](https://github.com/dotnetcore/CAP/assets/115682529/f6e06bd3-8634-49d2-a76b-26a0685a2938)

When i comment out my builder.Services.AddCap method and deploy to azure:
![image](https://github.com/dotnetcore/CAP/assets/115682529/e67e7281-1b77-46a2-b1fd-c47f38b155df)

When i performance test this, there  are no spikes (except for the cold start at the start). Something seems to be interfering with CAP and asynchronous request calls even though it doesnt use CAP!
![image](https://github.com/dotnetcore/CAP/assets/115682529/6522de00-8c7d-4eb0-9f46-7179f434f5cd)

**Comment by preezie-yasir** [comment]
@yang-xiaodong Its not the CPU unfortunately. We recently upgraded our app services to .NET 8 and as soon as we deployed our app service that had CAP, our response time AVG vastly increased:
<img width="1491" alt="image" src="https://github.com/dotnetcore/CAP/assets/115682529/d4593281-453d-4556-ada4-be8192e62e44">

See Feb 15 and Feb 19 graphs. Our CPU usage graph remained the same 
<img width="1470" alt="image" src="https://github.com/dotnetcore/CAP/assets/115682529/a94c0b80-99c2-4d44-ab7c-199ea279f1cf">

Our Memory for our app service plan also remained consistent
<img width="1486" alt="image" src="https://github.com/dotnetcore/CAP/assets/115682529/81667cab-7647-4c35-b2de-5b1ca01e7b83">

Very rarely with any asynchronous api call, the response time would be vastly increased due to something to do with CAP as a service in .NET 8.

This needs to be looked into. Im not sure why this is being caused especially in azure environments only. Please if you can, can you replicate an environment in azure and do some performance testing on the Minimal APIs with and without CAP being added as a service and you can confirm the difference in response times differ at times for some odd reason.

**Comment by preezie-yasir** [comment]
@yang-xiaodong are we able to schedule a call over google meets or teams if possible with my manager Danny Wang? We can demonstrate the problem over a call for better understanding.
