### ISSUE TITLE
Considering adding support for RocketMQ ?

### ISSUE THREAD

**Issue by witskeeper** [dotnetcore/CAP#1557]
We are trying to help more Java developers embrace the .NET ecosystem, and the CAP component is something we consider great and necessary. Additionally, RocketMQ has a high adoption rate in the Java ecosystem in China. Therefore, can we consider adding support for RocketMQ?

**Comment by yang-xiaodong** [comment]
Hello,

We have no plan to support RcketMQ. If you're interested, you can create your own repository, It can be added to the official CAP document as an extension implemented by the community, so that other people can find it here through the document. If you want, you can submit a PR to modify the docs.

Docs path:

docs/content/user-guide/zh/storage/transport.md

Thanks
