### ISSUE TITLE
Outbox Only

### ISSUE THREAD

**Issue by muratyuceer** [dotnetcore/CAP#1606]
Hello, 

My goal is to use CAP, but only to implement the outbox pattern. I want to consume and process messages directly from RabbitMQ myself, without involving the cap.received table in between. How can I achieve this?

**Comment by yang-xiaodong** [comment]
CAP is highly integrated with the published and received database tables. If you do not use these tables, you will need to implement all storage functionalities yourself.

When business code consumption fails due to message context, using the received table does not block the processing of subsequent messages.
