### ISSUE TITLE
请问数据库可以支持sqlite吗？

### ISSUE THREAD

**Issue by beefsteak** [dotnetcore/CAP#182]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [ ] Bug
- [x] Requirement
- [ ] Feature or performance improvement

___
### Question
- What do you want to know?

___
### Bug
- Which version of CAP, OS and .NET Core?

- Which company or project?

- What happen?
If possible, provide a way for reproducing the error. e.g. demo application, component version.

___
### Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yuleyule66** [comment]
Not support SQLite

**Comment by yuleyule66** [comment]
Because SQLite is a miniature database, many transactional features are not fully supported and are not recommended for use in a production environment, so SQLite support is not on our RoadMap.If you want, you can create a community project to support SQLite, I would like to create a link on the home page, would you like to do that?
