### ISSUE TITLE
订阅消息记录建议

### ISSUE THREAD

**Issue by bao2314483** [dotnetcore/CAP#227]
`[CapSubscribe(CapQueueConfig.BaseService.Insurance.InsurancePacificOrder)]
        public async Task<string> Q_AddSucc(Guid Id)
        {
            var htorder = await ct.Set<InsurancePacificOrder>().FirstOrDefaultAsync(x => x.Id == Id);
            if (htorder == null)
                return "保险订单不存在";
            var torder = await this.Remote.TransportOrder.TransportOrderInfo.GetById(htorder.TransportOrderInfoId);
            if (torder.Data == null)
                return "运输订单不存在";
            var result = await this.Remote.TransportOrder.TransportOrderPayments.Add(new TransportOrderPaymentsAddReq()
            {
                TransportOrderInfoId = htorder.TransportOrderInfoId,
                Amount = htorder.Premium,
                BalanceId = torder.Data.ShipperGoodsSource.Balance_Id,
                BalanceType = torder.Data.ShipperGoodsSource.BalanceType,
                CreatePerson = "系统添加",
                PaymentType = PaymentType.ShouRu,
                PaymentUse = PaymentUse.InsuranceFee,
                PaymentDesc = EnumsHelper.GetEnumDescription(PaymentUse.InsuranceFee)
            });
            return result.ErrorStr;
        }`

这个订阅方法,我的建议是在消息记录表Received的Content字段新增订阅方法执行结果记录

**Comment by yang-xiaodong** [comment]
Why do you need this feature?

**Comment by bao2314483** [comment]
你想下如果处理消息虽然执行成功,但是因为业务原因实际这个消息没有真正完成消费,这个时候需要记录消费订阅类的返回值,这样就清楚知道业务到底为什么没有消费成功,当然也可以采用throw new Exception('xxxxx')这样形式阻止消息消费成功,但是感觉会触发错误日志记录,产生大量日志.

当然这个只是建议,因为我是从hangfire转移采用CAP才发现这个问题

**Comment by yang-xiaodong** [comment]
If the consumer execution does not throw an exception, the CAP considers it to be successful. The record return value belongs to the business logic and should be controlled by you instead of being stored in the message table. The responsibility of the message table is only responsible for recording the status of the message.

In addition, Hangfire and CAP are completely different things. I don't understand what you mean by `转移`?
