### ISSUE TITLE
CapTransaction 的 Commit 操作如何保证一致性？

### ISSUE THREAD

**Issue by justinshao** [dotnetcore/CAP#276]
`CapTransaction.Commit()` 方法需要提交数据库事务及发布消息，目前是先提交数据库事务，后发布消息。我看到这个方法似乎无法保证一致性。特别是存在如下情况：数据库事务提交成功（也就是说消息已存入本地消息表），但是发布消息却失败了。但是外部代码无法获知具体原因，它可能认为本地数据库事务失败了，那么就可能会尝试重试。这不仅会导致消息重复，而且是否还意味着，外部业务逻辑需要保证幂等性？

**Comment by yang-xiaodong** [comment]
I think your question is about the idempotence, the answer in #94

**Comment by yang-xiaodong** [comment]
Related issue : #29

**Comment by yang-xiaodong** [comment]
你的意思是发消息和数据库事务一致?  这是不可能的！ 我们只需要保证最终一致性即可

**Comment by justinshao** [comment]
我再描述得清楚一点，特别是存在如下情况：数据库事务 `dbTransaction.Commit()` 成功（这时候消息已存入本地消息表），但是发布消息 `Flush()` 却失败了。出现这种情况得时候，外部会捕获错误。我的问题是外部如何来得知具体是哪一步执行失败了？这可能导致外部代码重试，那么这不仅会导致本地消息重复这可能不是关键，关键是这也导致数据库事务也重试了，但是上面这种情况毕竟数据库事务已经提交成功了，这是不是意味着数据库事务需要保证幂等性？

**Comment by yang-xiaodong** [comment]
> 数据库事务 dbTransaction.Commit() 成功
The message status is `Scheduled`
> 但是发布消息 Flush() 却失败了
The message status is still `Scheduled`

The CAP will be retry  publish the message at the background service , if succcess the message status will changed to `Succeeded` otherwise keep `Scheduled` and wait for the next retry. 
We will not retry the database transaction

**Comment by justinshao** [comment]
谢谢作者回答，我理解了。目前的机制是首先保证消息存入本地消息表（用于后面重试），这个是和数据库事务一致的。Flush只是将消息推入发送队列，并不实际发布消息，所以Flush本身几乎不会出错。
