### ISSUE TITLE
Working with multiple instances of one service

### ISSUE THREAD

**Issue by cruisade** [dotnetcore/CAP#369]
Hello, i'm using kafka transport with postgres persistence in my service.
I have 3 instance of my service (in kubernetes) and one database for persistence (one table for all instances).  Instances subscribes for one topic in one subscriber group. One of instance crushes when process message. What is behavior of other instances? Is one or both take this message to proccess? 
What cases should pay attention with multiple instance of service?

**Comment by yang-xiaodong** [comment]
Hello @cruisade ,

When using Kafka as a Transport, the message consumed by the consumer instance depends on the number of Kafka partitions and the consumer group.

If you have three service instances, then ideally your Kafka partition should be greater than or equal to three to ensure that all instances are working.

As you said, one of the instances crashed. Can you provide a log so that we can check it out?

**Comment by cruisade** [comment]
All instance in one consumer group. 
Should i use 3 partition of topics for 3 instances? And why one partition is not an option?
And, my question not about crush instance, it's about fault tolerance, and behavior of other instances. 
As i understand, every instance have scheduler that monitor "received" table. Is it possible that two other instances start process message (of crushed instance) in same time, and will process one message two times?

**Comment by yang-xiaodong** [comment]
> Should i use 3 partition of topics for 3 instances? 
Yes, it's best practice

> Why one partition is not an option?
I can't get your point.

> Will process one message two times
Yes, there is this possibility, but only for failed messages. At this time, the idempotency of the consumer will work.

> or it is commited when subscriber finish his work?
Commited after the message is stored in the table, before executing the consumer
