### ISSUE TITLE
How to ensure the consumer method will not be executed twice when the consumer method succeeded but IFetchedMessage.RemoveFromQueue failed?

### ISSUE THREAD

**Issue by standardcore** [dotnetcore/CAP#37]
IFetchedMessage looks like using a transaction that independent of the consumer method. Here is a situation may happen : IFetchedMessage.RemoveFromQueue (commit transaction) has been failed and rolling back after consumer method succeeded (this record in the cap.queue has not been deleted). When next round began, a same consumer method will be execute.

**Comment by yuleyule66** [comment]
I have thought about this problem in the issue #29 , this scenario is only one of you say, because of we can not guarantee 100% will not be repeated processing a message, so we want message consumer  can support idempotent operation at their needed scenario, such as repetitive operation does not cause side effects. Other frameworks based MQ all are so.
