### ISSUE TITLE
need a swim-line diagram

### ISSUE THREAD

**Issue by mfjiang** [dotnetcore/CAP#377]
Can you provide a swim-line diagram between the message sender module, the persistence module, and the receiver module. This helps users understand how the CAP service works internally.

**Comment by yang-xiaodong** [comment]
Hello @mfjiang ,

We have provided a flow chart about the CAP how to work ,  you can find at the docs [home page](http://cap.dotnetcore.xyz).

We will gradually improve our documentation so that beginners can understand the inner principles and how it works. At the later time I can provide a swim-line diagram to show how it works in the sequence time.

Thanks for your feedback, Cheers!

**Comment by mfjiang** [comment]
thanks
