### ISSUE TITLE
RabbitMQ message headers

### ISSUE THREAD

**Issue by marrrschine** [dotnetcore/CAP#388]
When using CAP with RabbitMQ, can I somehow access the original message headers and properties and not just the payload?

**Comment by yang-xiaodong** [comment]
Hello @marrrschine ,

The current version does not have direct access to the message header. We are implementing this feature in the next release. 

You can subscribe this issue to receive notifications.

Thanks.

Related issue: #378, #374

**Comment by kexxxfeng** [comment]
It's glad to hear that the raw message will be accessed.

I implement the idempotence by `redis lock`. It depend on the identity of the message very much.

I have to send a `Guid` into the message in order to be used to filter repeated message by suberscribers.

Now I had a new idea to refactor those redundant code.

It's `AOP`, just like `Filter` in `MVC`

Enquire redis if the message identity was locked before the subscriber consume the message.

The fake code like this
```c#
/*  Startup.cs */
services.AddCap(options =>
{
    ...
    options.AddFilter(new IdempotenceValidator());
})
```
```c#
public class IdempotenceValidator: IMessageConsuming
{
    public override async Task<bool> Comsuming(MessageContext message)
    {
        /* Enquire the redis locker if the message.Id was locked */
    }
}
```

Is that idea avaliable?

**Comment by marrrschine** [comment]
ok, when will that be?
is the next release already scheduled?

**Comment by yang-xiaodong** [comment]
@marrrschine 
I've very busy recently. so it will take longer
