### ISSUE TITLE
Is there any consideration for sqlite?

### ISSUE THREAD

**Issue by colinin** [dotnetcore/CAP#427]
> I have integrated CAP into the front-end project, such as **Xamarin**, **WinForm**, these clients are generally not directly connected to the database, memory storage is not very good, all I want to store the cap message in the local **sqlite**

> I wrote a class library with reference to the implementation of MySql, but I don't know much about sqlite, maybe some syntax needs to be optimized.

**Comment by colinin** [comment]
![image](https://user-images.githubusercontent.com/35512826/68745608-ef873080-0631-11ea-89f6-9c804a9adcc1.png)

**Comment by yang-xiaodong** [comment]
Thank you for your feedback. According to my understanding, SQLite has poor support for transactions. If you only use it to store messages, then it doesn't matter.

Currently I don't have the energy to maintain too many database implementations, including Oracle, SQLite, etc..

If you are willing to keep open source, I can list your repository in the documentation so that people who need it can find it.

**Comment by colinin** [comment]
Ok, I uploaded it to my repository, I can't use it for the server.

**Comment by colinin** [comment]
https://github.com/colinin/DotNetCore.CAP.Sqlite

**Comment by colinin** [comment]
Ok, I uploaded it to my repository, it only works on the client level.

**Comment by yang-xiaodong** [comment]
I will add your repo to the docs, Cheers!

**Comment by yang-xiaodong** [comment]
docs updated!
