### ISSUE TITLE
Consumer message header reading support

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#472]
If you want to get the message header at the consumer, you can inject CapHeader in the subscription method.

```c#
public void Subscription(Object body,[FromCap]CapHeader header)
{
    // header is a readonly collection
}

```

**Comment by anujacharya997** [comment]
Hi, how can i levergae dependy injection in this
i my senerio
i have application project library
and infrastructre (clean code articheture)
i only want cap's reference in infra project
and want my application coupled from implementing messaging library

namespace AccountService.Application.EventHandler
{
    public interface IAgentCreatedHandler
    {
        Task Handle(AgentCreated command, object header);
    }
}

namespace AccountService.Infrastructre.EventHandler
{
    public class AgentCreatedHandler : ICapSubscribe, IAgentCreatedHandler
    {

        [CapSubscribe(nameof(AgentCreated))]
        public async Task Handle(AgentCreated command, [FromCap] CapHeader header)
        {
        }
 }
}
but due to the miss match in the signature i am unable to do so.
Is there any workaround here ?
I would really appreciate your thoughts on this.
Thanks.
