### ISSUE TITLE
Question about why reading message from database delay by 4 minutes

### ISSUE THREAD

**Issue by allanhboy** [dotnetcore/CAP#474]
为什么消息持久化到数据库后重新读取要等待4分钟,还不能自定义时间

**Comment by yang-xiaodong** [comment]
I do not know why you need this feature?

I can explain why we set up a delayed four minutes to read the message from the database.

By default, when the CAP is started, a retry thread is enabled. Instead, the retry thread reads unsent or failed messages from the database every 1 minute. This is a mechanism to ensure availability.

In some cases, if the message is directly read from the database in real time, it may have serious consequences, such as when the message is persisted and before it is sent, then its status is `Scheduled`. At this time, the retry thread will read the message and send it. This will cause repeated sending of messages. In order to solve this problem we set a delay of 4 minutes. This can try to avoid the problem of uncommitted messages being sent

**Comment by allanhboy** [comment]
可是我一使用事务同步事件的推送后,就必定会触发这可恶的4分钟机制,如果不使用事务推送就是瞬间执行

**Comment by allanhboy** [comment]
就是使用的eShopOnContainers的实例 
`public class OrderingIntegrationEventService : IOrderingIntegrationEventService
    {
        private readonly ICapPublisher _eventBus;
        private readonly OrderingContext _orderingContext;
        private readonly ILogger<OrderingIntegrationEventService> _logger;

        public OrderingIntegrationEventService(ICapPublisher eventBus,
            OrderingContext orderingContext,
            ILogger<OrderingIntegrationEventService> logger)
        {
            _orderingContext = orderingContext ?? throw new ArgumentNullException(nameof(orderingContext));
            _eventBus = eventBus ?? throw new ArgumentNullException(nameof(eventBus));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task AddAndSaveEventAsync(object evt)
        {
            _logger.LogInformation("----- Enqueuing integration event to repository ({@IntegrationEvent})", evt);

            _eventBus.Transaction.Begin(_orderingContext.GetCurrentTransaction().GetDbTransaction());
            await _eventBus.PublishAsync(evt.GetGenericTypeName(), evt);
        }
    }`

**Comment by yang-xiaodong** [comment]
你真是惜字如金啊，连自己环境都不提供，代码也不知道格式化。eShop是使用的 SQL Server 会自动检测事务提交Flush消息，其他数据库自己看源码吧，太气了！
