### ISSUE TITLE
If consumer fail, how to config message return to queue

### ISSUE THREAD

**Issue by LouieGuo** [dotnetcore/CAP#553]
If consumer fail, how to config message return to queue

**Comment by yang-xiaodong** [comment]
CAP does not provide dead letter queue support

**Comment by mviegas** [comment]
@yang-xiaodong would make sense to add this feature? I think that dead-lettering is a common issue with distributed/messaging systems. I'd be glad to help with it.

**Comment by yang-xiaodong** [comment]
@mviegas Since CAP will retry failed messages, this may cause the messages posted to the dead letter queue to become successful when retrying, so I think it is of little significance to post to the dead letter queue.

When the maximum retry threshold is reached, you can currently use `FailedThresholdCallback` to manually publish to the queue you want. We do not provide direct support for this.
