### ISSUE TITLE
Add NATS support

### ISSUE THREAD

**Issue by araxis** [dotnetcore/CAP#595]
Please add NATS support.
www.nats.io

**Comment by yang-xiaodong** [comment]
Hello @araxis ,

Before this, I didn't know NATS. I spent some time reading the docs, and I found that it is divided into two parts `NATS Server` and `NATS Streaming Server`.

First let's talk about the `NATS Server`,  According to the docs, it does not support  the persistence and manual acknowledge features. For CAP, no persistence is tolerable, but the lack of acknowledge support is unacceptably , because it may cause message lost. (An exception occurred before the message was saved to the table)

STAN Streaming provides persistence and manual manual acknowledge support, but our goal seems to be NATS.

What do you think of this?

**Comment by araxis** [comment]
first Sorry for my bad English!!!
you are right about Current version Of NATS. jetstream a new feature that is implementing ,merge NATS and NATS Streaming Capabilities.in fact ,at current time  the only choice is NATS Stream .but I don't think Jetstream changes Base Concept and make big differences. again sorry for my bad English!!!

**Comment by yang-xiaodong** [comment]
@araxis  I think we can using req/reply model for message reliability without NATS Streaming, I think it's a good way, more simpler and  clear. 

`supports/nats` branch already have the untested code, any suggestion or pull request is welcome

**Comment by yang-xiaodong** [comment]
After investigation, due to a small audience, we will suspend the merger of this feature.

If you need this feature, please vote under this issue.

**Comment by yang-xiaodong** [comment]
Supported in v5.0

**Comment by araxis** [comment]
thanks a lot.

**Comment by Wagimo** [comment]
Hello, do you have any example implementation for NATS with .Net Core?
The documentation is not clear when sending messages or how they are received and manipulated.
If you have something, it would be interesting if you shared it.
thank you
