### ISSUE TITLE
Custom serializer only used for interaction with message queue

### ISSUE THREAD

**Issue by pascal89** [dotnetcore/CAP#641]
Hi,
I implemented a custom serializer (System.Text) for interaction with the message queue (like described in https://cap.dotnetcore.xyz/user-guide/en/cap/serialization/)
All goes well when the Inbox/Outbox doesn't have to be used for a retry. When it does my custom serializer cannot serialize the deserialized json from the storage provider, because it is of type `Newtonsoft.Json.Linq.JObject` instead of the type I expected it to be.
To solve my problem I think the solution will be not to use the `DotNetCore.CAP.Serialization.StringSerializer` but the implemention of `DotNetCore.CAP.Serialization.ISerializer` for (de)serializing the message object in the storage provider.

What are your thoughts about it?

**Comment by yang-xiaodong** [comment]
When restoring types from storage, we cannot know the type of data, so JObject is used here

**Comment by pascal89** [comment]
The problem is the `Newtonsoft.Json` serializer does that. When using another serializer like described in https://cap.dotnetcore.xyz/user-guide/en/cap/serialization/ these kind of problems will occur when used only for sending the messages to the message queue.

**Comment by Mastermindzh** [comment]
@yang-xiaodong ,

You can have a look at the migration guide from [Microsoft](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#jsondocument-and-jsonelement-compared-to-jtoken-like-jobject-jarray) to solve that issue.

We'd be happy to provide help in the form of a PR as well. Just have to know whether you wish to support more than just the Newtonsoft serializer :smile:

**Comment by yang-xiaodong** [comment]
@pascal89   @Mastermindzh 

Yes, due to the reasons I described, there are still some shortcomings in custom serialization. Providing the implementation of ISerializer in the storage provider may not solve this problem I think.

Since the storage structure of the database is a serialized `Message` object, if it is in the database, we use a string for serialization. When deserializing, its type is a Message object, so it is impossible to know whether the Value field is a primitive type or a DTO object. What do you think about this?

PR is welcome, if it can solve this problem, Thanks

**Comment by yang-xiaodong** [comment]
Fixed in v3.1.1
