### ISSUE TITLE
Using CAP with Dapr

### ISSUE THREAD

**Issue by altinoren** [dotnetcore/CAP#662]
Dapr [1] encapsulates various message buses [2] and allows a unified pubsub model through a library as well as raw http/gRPC. CAP as an eventbus overlaps with this functionality, but Dapr alone does not support transactional event publishing, hence my question.

I'd like to use Dapr  (as the transport) and CAP together on publishing side, a possible scenario:
- User publishes to CAP in a transaction.
- CAP publishes to Dapr.
  - Dapr returns 200, guaranteeing at least once delivery.
- Dapr delivers the message in it's own way to the subscriber.

Is this scenario possible? Do we need something like `DotNetCore.CAP.Dapr` for this scenario? 

[1] https://github.com/dapr/dapr/
[2] https://github.com/dapr/docs/tree/master/howto/setup-pub-sub-message-broker#reference

**Comment by yang-xiaodong** [comment]
Hello @altinoren ,

I don’t know much about Dapr. Yes, in theory, if Dapr is treated as a Broker, then `DotNetCore.CAP.Dapr` project is needed for adaptation.

I checked the SDK of Dapr, and it seems that `Ack` and `Reject` are not provided to confirm or reject the message so that it can be received again. In addition the consumer of CAP inherits from `ICapSubscribe`, which seems to conflict with the inherit object of Dapr Actor, so I am not sure if it can be.

**Comment by lefig** [comment]
Hi,

I was wondering whether this feature was progressed?

Thanks

Fig

**Comment by yang-xiaodong** [comment]
@lefig This is our community's extension for CAP, and you can refer it

https://github.com/zlzforever/MSFramework/tree/master/src/DotNetCore.CAP.Dapr
