### ISSUE TITLE
The message record table can‘t auto clear

### ISSUE THREAD

**Issue by cocosip** [dotnetcore/CAP#689]
.net env: .net core 3.1
cap version: `DotNetCore.CAP.PostgreSql` v3.1.1 , `DotNetCore.CAP.Kafka` v3.1.1

In our production env, we found that `received`  table can't clear the successed message from persistent, and we also found kafka consumer offset is incorrect.
![1](https://user-images.githubusercontent.com/9337837/96392013-46579b80-11ed-11eb-88e1-a55164737728.png)

![kafka2](https://user-images.githubusercontent.com/9337837/96392133-b1a16d80-11ed-11eb-8b58-a8cfd9f104f1.png)

**Comment by yang-xiaodong** [comment]
Hello, 

According to your description, we can't reproduce it

**Comment by cocosip** [comment]
> Hello,
> 
> According to your description, we can't reproduce it

Thank you for your attention,  I am try to collection more information about this problem.

**Comment by cocosip** [comment]
Today, we restart kafka broker,and we found that kafka consumption schedule back to normal ,and one of the database's `received` table only have latest data , It seem work well ! &nbsp;&nbsp;  We wonder what the hell is this cause , our guess is the result of the database.  Previous versions of our code has some problems, resulting in a lot of error messages appear and try again. Huge amounts of data has led to the slow query , eventually leading to our table had 70 million records, and contains a lot of data that has been sent successfully.
&nbsp;&nbsp;  We hope CAP could create some datatable indexes when initialized automatically when creating a database. (Every day we generate about 20 million messages).
&nbsp;&nbsp;  It's better to use different database in different producer/consumer app ,  especially when large data volume.
Thank you!

**Comment by yang-xiaodong** [comment]
Hello, thank you for your feedback, let me answer your questions.

According to your description, it seems that there was an error in your application code, which caused a large number of messages to not be executed successfully, and then due to the backlog of a large number of messages, there was an abnormal corresponding problem in the database.

CAP is designed to transmit business transactional messages. There are a lot of record messages in your scenario. I think these messages have performance requirements and I suggest that you can optimize this or directly connect to Kafka without using CAP.

In most cases, adding indexes may lead to improved query performance, but it will reduce write and update performance. Since the Published and Received tables used by CAP are highly written and updated, I do not recommend adding too many indexes

**Comment by cocosip** [comment]
Thank you !
