### ISSUE TITLE
Replace Newtonsoft.Json to System.Text.Json

### ISSUE THREAD

**Issue by yang-xiaodong** [dotnetcore/CAP#740]
In version 5.0 , we will replace Newtonsoft.Json to System.Text.Json to improve performance

**Comment by ml-eds** [comment]
This should be mentioned as a "Breaking Change" in the release notes of version 5, IMHO. 

We had a hard time adjusting to this (moving from version 3 to 6), because our event objects weren't properly serialized anymore (because of fields vs. properties, encoding and collection type problems).

For anyone having the same problem: Read this very carefully: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-6-0

Or just use the last version 3 serializer code as custom serializer, as described here

https://github.com/dotnetcore/CAP/issues/1005

and here

https://cap.dotnetcore.xyz/user-guide/en/cap/serialization/
