### ISSUE TITLE
Question about IDbContextTransaction  extension methods

### ISSUE THREAD

**Issue by Goleven** [dotnetcore/CAP#747]
英文水平有限,请允许我使用中文😅

你好 @yang-xiaodong.
首先感谢您提供cap 这个非常好用的组件.
我是这几天在尝试使用cap写了几个小的样例， 准备之后在我的项目中正式使用他。
在用到事务的时候， 我这边有一点小的疑问，
1. 由cap来的扩展方法来创建一个 IDbContextTransaction 对象的这种方式，如果换成由cap 来接受一个IDbContextTransaction对象会不会更好一些。
2. BeginTransaction 中的 “autoCommit”参数，虽然这个参数是可选的，在我的理解中cap应该是更关注消息的传递这一块， 如果我使用cap来帮我提交业务代码，在职责会不会有一些模糊。

可能表达上没那么的条理清晰， 不要介意😶😶😶

**Comment by yang-xiaodong** [comment]
Hello, let me answer you question,

> 由cap来的扩展方法来创建一个 IDbContextTransaction 对象的这种方式，如果换成由cap 来接受一个IDbContextTransaction对象会不会更好一些

I think the extension method is more in line with the user experience. Of course, you can ignore the extension method to encapsulate and pass in IDbContextTransaction by yourself. This is entirely up to you.

> BeginTransaction 中的 “autoCommit”参数，虽然这个参数是可选的，在我的理解中cap应该是更关注消息的传递这一块， 如果我使用cap来帮我提交业务代码，在职责会不会有一些模糊。

AutoCommit aims to provide a simple way to help commit transactions, because it is still attached to the ICapTransaction object, so I think its responsibilities are clear
