### ISSUE TITLE
Publish and Subscribe functionality using object types.

### ISSUE THREAD

**Issue by alirezamahmoudi** [dotnetcore/CAP#762]
It is required to publish events based on their types and correspondingly subscribe to events using their types. So, we can separate all events and handlers

**Comment by yang-xiaodong** [comment]
Hello, considering the heterogeneous (different languages) service in microservices, CAP has not based on types to publish and subscribe from the beginning of its design, this is by design.

I personally think that event handling is also part of the business service, and there is no need to isolate them and treat them differently.
