### ISSUE TITLE
Compatibility between 2.6.0 and 5.0.1

### ISSUE THREAD

**Issue by zemien** [dotnetcore/CAP#847]
Advice needed.

We have a few microservices using CAP 2.6.0. We are building new microservices that consume these existing events, and publish new ones too.

We want to use the latest CAP 5.0.1 but we can't because it won't be able to subscribe to the events that were published using 2.6.0 (due to the [breaking changes in 3.0.0](https://github.com/dotnetcore/CAP/releases/tag/v3.0.0)).

What is the suggested path to get compatibility? 

The easiest way is to migrate everything to 5.0.1 but we don't have the resources to do that right now.

**Comment by yang-xiaodong** [comment]
Hello,

In version 2.6, the message is packaged by CAP and then serialized as json and sent to the message queue, and the consumer is also unpacked by CAP and then deserialized into the corresponding object.

This will cause two problems. One is the inability to customize the serialization of messages, and the other is that users need to perform additional adaptation work when consuming messages sent by other clients.

Based on the above reasons, we adjusted the data structure and storage method of sending and consumption. Use a more native way to achieve. The message you send will be directly serialized and delivered to the body of the message queue, and the metadata information will be delivered to the header of the message queue.

The data structure of the database has not changed in version 3.0. During the upgrade process, it is necessary to ensure that all messages in the old format have been successfully consumed, so that the new version will not fail to read messages in the old format.

**Comment by zemien** [comment]
Thanks, I have a better understanding now. CAP >= 3.0.0 is almost a different backend altogether, that's why it's not compatible.
