### ISSUE TITLE
How can I avoid "Connection close forced" warning?

### ISSUE THREAD

**Issue by flipdoubt** [dotnetcore/CAP#850]
Our logs are starting to accumulate "RabbitMQ client connection closed! --> Connection close forced" warnings from DotNetCore.CAP.RabbitMQ.ConnectionChannelPool, so we configured that source to only log errors. Beyond that, what is the proper way to shutdown without creating these warnings when `IBootstrapper.BootstrapAsync` is the primary API we use to control CAP? Is there an analogous `ShutdownAsync` somewhere?

**Comment by yang-xiaodong** [comment]
These warning logs currently come from RabbitMQ events that we subscribe to. We currently do not provide an option to close them and I think using filters in the logs is a correct way.

However, I checked the warning log "Connection close forced" which was displayed when the application started. This log was introduced by the change made by #808. Do we consider removing the ConnectionShutdown subscription in order to close this log? I think this is reasonable. What do you think?   @flipdoubt @xiangxiren

**Comment by xiangxiren** [comment]
If it is an irrelevant log. I am in favor of closing it.
