### ISSUE TITLE
Supporting Saga

### ISSUE THREAD

**Issue by meysamhadeli** [dotnetcore/CAP#959]
Hi.
Do you have any plan to support saga?

**Comment by yang-xiaodong** [comment]
Hello, 

we do not have this plan in the short term. using Saga requires users to have a correct understanding of it and reasonably split the business process, and then use the flowchart to describe and generate json to let the program execute. Obviously, the entire processing process needs to be monitored, which is a complicated work .

Currently you can manually organize the state process rules in each service instead of focusing on the entrance.
